### ISSUE TITLE
Latest build "btgzvrzsm4ryv7vxaxf8v2g" broken

### ISSUE THREAD

**Issue by ngraf** [zaquestion/docker-sonarqube-scanner#1]
Your build https://hub.docker.com/r/zaquestion/sonarqube-scanner/builds/btgzvrzsm4ryv7vxaxf8v2g/ is broken.

How to reproduce?

```
$ docker run -it --rm -v $(pwd):/var/www zaquestion/sonarqube-scanner:latest
/bin/sh: sonar-scanner: not found
```

Reason for bug:
The folder in the zip https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.0.3.778.zip
has been renamed from "sonar-scanner-cli-X.Y.Z" to "sonar-scanner-X.Y.Z".
This is not compatible with current implementation of the Dockerfile.

**Comment by zaquestion** [comment]
Thanks for the detailed report, I'll fix this up right away

**Comment by zaquestion** [comment]
@ngraf This should be fix in: https://hub.docker.com/r/zaquestion/sonarqube-scanner/builds/bpsyfwndtxtqca6shzilovb/  -- Feel free to reach out if there are any other issues.

**Comment by ngraf** [comment]
Thanks, it's fixed now. 

Nevertheless I lost trust. I now now use "newtmitch/sonar-scanner", that has tagged docker images.

**Comment by zaquestion** [comment]
@ngraf That's a good point. I wrote this as a one off, ironically because newtmitch's was outdated, broken and produced inefficient images circa late 2016. Honestly I haven't used sonarqube since and looks like he's put quite a bit more work now. With that in mind I'll update the readme to point folks to his stuff and archive the repo. Thanks again for the heads up, pretty annoying to have had a broken build sitting in the wild.
